/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.studentGradeBUS;
import DAO.courseDAO;
import DAO.personDAO;
import DTO.courseDTO;
import DTO.personDTO;
import DTO.studentGradeDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class addNewStudentGrade extends javax.swing.JFrame {

    /**
     * Creates new form addNewStudentGrade
     */
    
    //GỌi BUS
    studentGradeBUS studentGrade_BUS ;
    
    
    //Khởi tạo BUS
    private void khoiTaoBus(){
        try {
            studentGrade_BUS = new studentGradeBUS();
            System.out.println("GUI.courses.khoiTaoBus() khởi tạo BUS oke");
        } catch (Exception e) {
            System.out.println("GUI.courses.khoiTaoBus() Error : "+e.getMessage());
        }
    }
    
    public addNewStudentGrade() {
        initComponents();
        khoiTaoBus();
        showCbbStudent();
        showCbbCourseTitlet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbStudent = new javax.swing.JLabel();
        jlbCourse = new javax.swing.JLabel();
        jlbGrade = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        cbbCourse = new javax.swing.JComboBox<>();
        cbbStudent = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jlbDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbStudent.setText("Student");

        jlbCourse.setText("Course");

        jlbGrade.setText("Grade");

        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        cbbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCourseActionPerformed(evt);
            }
        });

        cbbStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbStudentActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jlbDisplay.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbbStudent, 0, 263, Short.MAX_VALUE)
                            .addComponent(cbbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGrade))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStudent)
                    .addComponent(cbbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCourse)
                    .addComponent(cbbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGrade)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jlbDisplay)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng cửa sổ không?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbStudentActionPerformed
        // TODO add your handling code here:
//        jlbDisplay.setText((String) cbbStudent.getSelectedItem());

    }//GEN-LAST:event_cbbStudentActionPerformed

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Kiểm tra đầu vào của grade
        String grade_string = txtGrade.getText();
        while(grade_string.isEmpty() || !grade_string.matches("-?\\d+(\\.\\d+)?")){
              
            JOptionPane.showMessageDialog(null, grade_string + " : Không phải là số");
            return;

        }
        Float grade = Float.parseFloat(txtGrade.getText());
        while (grade > 4 || grade < 0) {            
            JOptionPane.showMessageDialog(null, grade + " : Điểm không hợp lệ");
            return;
        }

        String studentName = (String) cbbStudent.getSelectedItem(); // Lấy string cbb
        String[] studentNames = studentName.split("Name : ");   // Cắt lấy tên học sinh
        String courseTitle = (String) cbbCourse.getSelectedItem();
        String[] courseTitles = courseTitle.split("Title : ");
        // Hỏi trước khi lưu
        if (JOptionPane.showConfirmDialog(null, "New Add :\n"+studentNames[1] + "    " + courseTitles[1] + "   " + txtGrade.getText(), "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String[] studentIDs = studentName.split(" "); // Lấy chuỗi cắt " " lấy ra ID ở vị trí 2
            String[] courseIDs = courseTitle.split(" "); // Lấy chuỗi cắt " " để lấy ra ID ở vị trí 2
            studentGradeDTO newStudentGradeDTO = new studentGradeDTO();
//            System.out.println(courseIDs[2]+""+studentIDs[2]);  // xem thử đúng không
            // Tạo mới 1 đối tượng studentGrade
            newStudentGradeDTO.setCourseID(Integer.parseInt(courseIDs[2]));
            newStudentGradeDTO.setStudenID(Integer.parseInt(studentIDs[2]));
            newStudentGradeDTO.setGrade(grade);
            try {
                studentGrade_BUS.add(newStudentGradeDTO);
                
            } catch (Exception e) {
                e.getStackTrace();
            }
            dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbCourseActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
//        String studentName = (String) cbbStudent.getSelectedItem();
//        String[] studentNames = studentName.split("Name : ");
//        String courseTitle = (String) cbbCourse.getSelectedItem();
//        String[] courseTitles = courseTitle.split("Title : ");
//        jlbDisplay.setText(""+studentNames[1] + "    " + courseTitles[1] + "   " + txtGrade.getText() );
//          String grade_string = txtGrade.getText();
//          if(grade_string.isEmpty() || !grade_string.matches("\\d+")){
//              
//              JOptionPane.showMessageDialog(null, grade_string + " : Không phải là số");
//              return;
//              
//          }
//        int grade = Integer.parseInt(txtGrade.getText());
    }//GEN-LAST:event_txtGradeActionPerformed

    
    // Hiển thị combobox 
    private void showCbbStudent(){
        personDAO prsDAO = new personDAO();
        
        try {
            ArrayList<personDTO> arr_person = new ArrayList<>();
            arr_person = prsDAO.getAll();
            for(personDTO person : arr_person){
                if(person.getEnrollmentDate()!=null)
//                    items.add("ID : " + person.getPersonID() + " Name : " + person.getFirstName() + " " + person.getLastName());
                    cbbStudent.addItem("ID : " + person.getPersonID() + " Name : " + person.getFirstName() + " " + person.getLastName());
            }
//            System.out.println(""+items);
//            String[] itemsString = items.toArray(new String[items.size()]);
            
        } catch (Exception e) {
            e.getStackTrace();
        }
//      cbbStudent = new JComboBox<>(itemsString);
    }
    
    // Hiển thị combobox 
    private void showCbbCourseTitlet(){
        courseDAO crDAO = new courseDAO();
        
        try {
            ArrayList<courseDTO> arr_courses = new ArrayList<>();
            arr_courses = crDAO.getAll();
            for(courseDTO course : arr_courses){
                cbbCourse.addItem("ID : " + course.getCourseID() + " Title : " + course.getCoureTitle());  // cbb add item
            }

            
        } catch (Exception e) {
            e.getStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewStudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewStudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewStudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewStudentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addNewStudentGrade add = new addNewStudentGrade();
                add.setLocationRelativeTo(null);
                add.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbbCourse;
    private javax.swing.JComboBox<String> cbbStudent;
    private javax.swing.JLabel jlbCourse;
    private javax.swing.JLabel jlbDisplay;
    private javax.swing.JLabel jlbGrade;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JTextField txtGrade;
    // End of variables declaration//GEN-END:variables
}
