/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.courseBUS;
import BUS.studentGradeBUS;
import DTO.courseDTO;
import DTO.studentGradeDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class studentGrade extends javax.swing.JFrame {

    //Tạo một model để đựng dữ liệu của table
    DefaultTableModel model_studentGrade = new DefaultTableModel();
    // Tạo một arr để đựng data tìm kiếm
    ArrayList<studentGradeDTO> arr_studentGrades_find = new ArrayList<>();
    // Tạo 1 model để đựng dữ table tìm kiếm
//    DefaultTableModel model_studentGrade_find = new DefaultTableModel();
//GỌi BUS
    studentGradeBUS studentGrade_BUS ;
    
    
    //Khởi tạo BUS
    private void khoiTaoBus(){
        try {
            studentGrade_BUS = new studentGradeBUS();
//            System.out.println("GUI.studentGrade.khoiTaoBus() khởi tạo BUS oke");
        } catch (Exception e) {
            System.out.println("GUI.studentGrade.khoiTaoBus() Error : "+e.getMessage());
        }
    }
        
    /**
     * Creates new form studentGrade
     */
    public studentGrade() {
        initComponents();
        this.setLocationRelativeTo(null);  //Chính giữa màn hình
        khoiTaoBus();
        //init data for tbl
        khoiTao_tbl_StudentGrade();
        //khởi tạo cbb course
    }
    
    
    private void khoiTao_tbl_StudentGrade(){
        //tạo    mới 1 model
        model_studentGrade = new DefaultTableModel();
        
        // Tao cot dau tien
        String column[] = {"EnrollmentID", "CourseID", "StudentID", "Grade"};
        model_studentGrade.setColumnIdentifiers(column);
        
        try {
            ArrayList<studentGradeDTO> listStudentGrades = studentGrade_BUS.getStudentGradesAll();
            //Set du lieu vao table
            set_TableData_StudentGrade(listStudentGrades);
        } catch (Exception e) {
            e.getStackTrace();
//            System.out.println("GUI.studentGrade.khoiTao_tbl_StudentGrade() Error : "+ e.getMessage() + e.getStackTrace());
            JOptionPane.showMessageDialog(null, "GUI.studentGrade.khoiTao_tbl_StudentGrade() Lỗi xảy ra: " + e.getMessage(),
        "Thông báo", JOptionPane.ERROR_MESSAGE); // Hiển thị thông báo lỗi cho người dùng
        }
        
        tblStudenGrade.setModel(model_studentGrade);
        
        
    }
    
    // Hàm dùng để set dữ liệu thông tin sách vào model của Table StudentGrade
    private void set_TableData_StudentGrade(ArrayList<studentGradeDTO> listStudentGrades){
        for(studentGradeDTO studentGrade : listStudentGrades){
            model_studentGrade.addRow(new Object[]{studentGrade.getEnrollmentID(),studentGrade.getCourseID(), studentGrade.getStudenID()
                    ,studentGrade.getGrade()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEnrollmentID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCourseID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudenGrade = new javax.swing.JTable();
        btnFind = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(122, 122, 0));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1Layout.columnWeights = new double[] {0.0};
        jPanel1Layout.rowWeights = new double[] {0.0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Courses Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 328, 0, 291);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("EnrollmentID");

        txtEnrollmentID.setText("0");

        jLabel4.setText("CourseID");

        jLabel5.setText("StudenID");

        jLabel6.setText("Grade");

        txtGrade.setText("0");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        btnUpdate.setText("Update");

        btnExit.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnUpdate)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnrollmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExit)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEnrollmentID))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addGap(33, 33, 33)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(23, 23, 23))
        );

        tblStudenGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EnrollmentID ", "CourseID", "StudentID", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblStudenGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudenGradeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudenGrade);

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel3.setText("Find");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFind)
                        .addComponent(jLabel3)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Click row trong tablbe
    private void tblStudenGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudenGradeMouseClicked
        // TODO add your handling code here:
        int row = tblStudenGrade.getSelectedRow();
        try {
                studentGradeDTO studentGrade = new studentGradeDTO();
            if(arr_studentGrades_find.isEmpty()){
                studentGrade = studentGrade_BUS.getStudentGradesAll().get(row);
            }else{
                studentGrade = arr_studentGrades_find.get(row);
            }
                txtEnrollmentID.setText(studentGrade.getEnrollmentID()+"");
                txtGrade.setText(studentGrade.getGrade()+"");
                txtCourseID.setText(studentGrade.getCourseID() + " Title : " + studentGrade_BUS.getTitleCourse(studentGrade.getCourseID()));
                txtStudentID.setText(studentGrade.getStudenID() + " Name : " + studentGrade_BUS.getNameStudent(studentGrade.getStudenID()));
                
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_tblStudenGradeMouseClicked

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        if(txtFind.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nhập dữ liệu tìm kiếm!");
            return;
        }
        String id_student_find = txtFind.getText();
        String column[] = {"EnrollmentID", "CourseID", "StudentID", "Grade"};
        
        DefaultTableModel model_studentGrade_find = new DefaultTableModel();
        model_studentGrade_find.setColumnIdentifiers(column);
        
        try {
            arr_studentGrades_find = studentGrade_BUS.getStudentGradeFind(id_student_find);
            for(studentGradeDTO studentGrade : arr_studentGrades_find){
                model_studentGrade_find.addRow(new Object[]{studentGrade.getEnrollmentID(),studentGrade.getCourseID(), studentGrade.getStudenID()
                    ,studentGrade.getGrade()});
            }
            
            if(arr_studentGrades_find.isEmpty()){
                JOptionPane.showMessageDialog(this, "Học sinh mã : " + id_student_find + "không có điểm" );
                return;
            }else{
                tblStudenGrade.setModel(model_studentGrade_find);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // Reset table
        tblStudenGrade.setModel(model_studentGrade);
        // Reset listFind
        arr_studentGrades_find = new ArrayList<>();
        //reset txtFind
        txtFind.setText(null);
        studentGrade stdGrade =  new studentGrade();
        stdGrade.setLocationRelativeTo(null);
        stdGrade.setDefaultCloseOperation(EXIT_ON_CLOSE);
        stdGrade.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addNewStudentGrade aNSt = new addNewStudentGrade();
        aNSt.setLocationRelativeTo(null);
        aNSt.setDefaultCloseOperation(EXIT_ON_CLOSE);
        aNSt.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void showCbbCourse(){
        
//        courseBUS crBUS = new courseBUS();
////        DefaultComboBoxModel courseTitle = new DefaultComboBoxModel();
//        try {
//            ArrayList<courseDTO> arr_courses = crBUS.getCoureseAll();
//            for(courseDTO crDTO : arr_courses){
////                courseTitle.addElement(crDTO.getCoureTitle());
//                  cbbCourseTitle.addItem(crDTO.getCoureTitle()+"");
//            }
////            cbbCourseID.setSelectedItem("");
//            
//        } catch (Exception e) {
//            e.getStackTrace();
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentGrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                studentGrade stdGrade =  new studentGrade();
                stdGrade.setLocationRelativeTo(null);
                stdGrade.setDefaultCloseOperation(EXIT_ON_CLOSE);
                stdGrade.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudenGrade;
    private javax.swing.JLabel txtCourseID;
    private javax.swing.JLabel txtEnrollmentID;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JLabel txtStudentID;
    // End of variables declaration//GEN-END:variables
}
